<?php
// $Id$

/**
 * @file
 * Universal word/phrase linking a.k.a. glossary.
 */

/**
 * Term type.
 */
define('INTERLINK_TYPE_ABBREVIATION', 1);
define('INTERLINK_TYPE_SYNONYM',      2);

/**
 * Implementation of hook_form_alter().
 */
function interlink_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    // @todo Node type selection.
  }
  elseif (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] .'_node_form' == $form_id) {
    $node = $form['#node'];
    if (!empty($node->nid)) {
      $terms = interlink_load_terms('node', $node->nid);
    }
    $form['interlink'] = array(
      '#type' => 'fieldset',
      '#title' => t('InterLink settings'),
      '#tree' => TRUE,
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['interlink']['abbreviations'] = array(
      '#type' => 'textarea',
      '#title' => t('Abbreviations'),
      '#default_value' => isset($terms['abbreviations']) ? implode("\n", $terms['abbreviations']) : '',
    );
    $form['interlink']['synonyms'] = array(
      '#type' => 'textarea',
      '#title' => t('Synonyms'),
      '#default_value' => isset($terms['synonyms']) ? implode("\n", $terms['synonyms']) : '',
    );
    $form['#validate'][] = 'interlink_node_form_validate';

    if (module_exists('vertical_tabs')) {
      // Add javascript tp provide vertical tabs summary callbacks.
      drupal_add_js(drupal_get_path('module', 'interlink') .'/interlink.node_form.js');
    }
  }
}

function interlink_node_form_validate($form, &$form_state) {
  //$synonyms = explode("\n", $form_state['values']['interlink']['synonyms']);
}

function interlink_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'insert' || $op == 'update') {
    foreach (interlink_get_types() as $type) {
      $node->interlink[$type] = explode("\n", $node->interlink[$type]);
    }
    interlink_save_terms('node', $node->nid, $node->title, $node->interlink);
  }
}

/**
 * Implementation of hook_init().
 */
function interlink_init() {
  drupal_add_css(drupal_get_path('module', 'interlink') .'/interlink.css');
}

/**
 * Implementation of hook_filter().
 */
function interlink_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('InterLink filter'));

    case 'description':
      return t('Interlink words or phrases.');

    case 'process':
      return interlink_filter_process($text, $format);

    case 'no cache':
      // @todo Testing only.
      return TRUE;

    default:
      return $text;
  }
}

/**
 * Filter text.
 */
function interlink_filter_process($text, $format) {
  // Get regular expression.
  if ($cache = cache_get('interlink:rx')) {
    $regex = $cache->data;
  }
  else {
    // Rebuild regular expression.
    $terms = array();
    $result = db_query("SELECT term FROM {interlink_term} ORDER BY CHAR_LENGTH(term) DESC");
    while ($row = db_fetch_array($result)) {
      $terms[] = preg_quote($row['term'], '/');
    }
    $regex = implode('|', $terms);
    cache_set('interlink:rx', $regex);
    unset($terms);
  }
  if (!$regex) {
    return $text;
  }

  $excluded_tags = variable_get('interlink_excluded_tags', array('a', 'abbr', 'acronym'));

  // Create a DOM object from the text.
  $html = str_get_html($text);

  // Process all DOM text nodes.
  foreach ($html->find('text') as $element) {
    // Traverse up the tree to exclude conflicting parent tags.
    $parent = $element->parent;
    do {
      if (in_array($parent->tag, $excluded_tags)) {
        // Skip this element.
        continue 2;
      }
    } while ($parent = $parent->parent);

    // @todo What about single quotes in matched text?
    $element->innertext = preg_replace('/\b(' . $regex . ')/ue', "_interlink_filter_replace('\\1')", $element->innertext);
  }

  return $html->save();
}

/**
 * Helper function to replace a matched phrase.
 */
function _interlink_filter_replace($match) {
  $term = interlink_load_term($match);
  $text = '<abbr title="' . check_plain($term->title) . '">' . $match . '</abbr>';
  $url = $term->object_type . '/' . $term->object_id;
  return l($text, $url, array('attributes' => array('class' => 'interlink interlink-'. $term->object_type), 'html' => TRUE));
}

/**
 * Helper function; return list of types for terms.
 */
function interlink_get_types() {
  return array(
    INTERLINK_TYPE_ABBREVIATION => 'abbreviations',
    INTERLINK_TYPE_SYNONYM => 'synonyms',
  );
}

/**
 * @defgroup interlink_crud InterLink CRUD functions
 * @{
 */

/**
 * Load one term.
 *
 * @param $term
 *   A term string.
 * @return
 *   A term definition record.
 */
function interlink_load_term($term) {
  return db_fetch_object(db_query("SELECT te.*, ti.title FROM {interlink_term} te LEFT JOIN {interlink_title} ti ON ti.object_type = te.object_type AND ti.object_id = te.object_id WHERE te.term = '%s'", $term));
}

/**
 * Load terms for an object.
 *
 * @param $object_type
 *   The object type to load terms for.
 * @param $object_id
 *   The object id to load terms for.
 * @return
 *   An array of terms, separated by type.
 */
function interlink_load_terms($object_type, $object_id) {
  $terms = array(
    'abbreviations' => array(),
    'synonyms' => array(),
  );
  $types = interlink_get_types();
  $result = db_query("SELECT term, type FROM {interlink_term} WHERE object_type = '%s' AND object_id = %d", $object_type, $object_id);
  while ($row = db_fetch_array($result)) {
    $terms[$types[$row['type']]][] = $row['term'];
  }
  return $terms;
}

/**
 * Save abbreviations and synonyms of an object.
 *
 * @param $object_type
 *   The object type to save terms for.
 * @param $object_id
 *   The object id to save terms for.
 * @param $object_title
 *   The unabbreviated title of the object.
 * @param $terms
 *   An array of terms.
 */
function interlink_save_terms($object_type, $object_id, $object_title, array $terms) {
  // Clean data.
  foreach (interlink_get_types() as $type) {
    foreach ($terms[$type] as $key => $value) {
      if (trim($value) == '') {
        unset($terms[$type][$key]);
        continue;
      }
      // Strip carriage return leftovers on Windows OS.
      $terms[$type][$key] = str_replace("\r", '', $value);
    }
  }
  // No need to flush caches if nothing changed.
  if ($terms == interlink_load_terms($object_type, $object_id)) {
    return;
  }

  // Delete existing data.
  db_query("DELETE FROM {interlink_term} WHERE object_type = '%s' AND object_id = %d", $object_type, $object_id);
  db_query("DELETE FROM {interlink_title} WHERE object_type = '%s' AND object_id = %d", $object_type, $object_id);

  // Store terms.
  foreach (interlink_get_types() as $type_int => $type) {
    foreach ($terms[$type] as $term) {
      $record = array(
        'object_type' => $object_type,
        'object_id' => $object_id,
        'term' => $term,
        'type' => $type_int,
      );
      drupal_write_record('interlink_term', $record);
    }
  }

  // Store object title.
  $record = array(
    'object_type' => $object_type,
    'object_id' => $object_id,
    'title' => $object_title,
  );
  drupal_write_record('interlink_title', $record);

  // Flush related cashes.
  cache_clear_all('interlink:rx', 'cache');
  cache_clear_all('*', 'cache_filter', TRUE);
  cache_clear_all('*', 'cache_block', TRUE);
  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * @} End of "defgroup interlink_crud".
 */
