<?php
// $Id$

/**
 * @file
 * Contains the definition list style plugin.
 */

/**
 * Style plugin to render each item in a definition list.
 *
 * @ingroup views_style_plugins
 */
class interlink_views_plugin_style_definition_list extends views_plugin_style {
  /**
   * Set default options
   */
//  function option_definition() {
//    $options = parent::option_definition();
//
//    $options['type'] = array('default' => 'ul');
//
//    return $options;
//  }

  /**
   * Render the given style.
   */
//  function options_form(&$form, &$form_state) {
//    parent::options_form($form, $form_state);
//    $form['type'] = array(
//      '#type' => 'radios',
//      '#title' => t('List type'),
//      '#options' => array('ul' => t('Unordered list'), 'ol' => t('Ordered list')),
//      '#default_value' => $this->options['type'],
//    );
//  }
}

